### ISSUE TITLE
When my data is CatYeaNum map_colors stops working

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/paletero#6]
Only stop working when the year don't have NA

data <- sample_data("Cat-Yea-Num", addNA= FALSE)
 f <- homodatum::fringe(data)
  nms <- fringe_labels(f)
  d <- fringe_d(f)
paletero::map_colors(d, 'a', palette, colors_df = NULL)

**Comment by jpmarindiaz** [comment]
Is this the error you get?
```
paletero::map_colors(d, color_by = 'a', palette, colors_df = NULL)
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
```
I get that error when I don't include the `palette` parameter. Setting the palette should work
 
```
paletero::map_colors(d, color_by = 'a', palette = "Set1", colors_df = NULL)
```
